[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = ""
  hostname = ""
  omit_hostname = false

[[inputs.docker]]
  # Замість unix:///var/run/docker.sock використовуємо мережеву адресу проксі
  endpoint = "tcp://docker-proxy:2375"
  timeout = "5s"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"